public class Edificio{

    private static final String NON_METHOD = 'FFFFFF LOCAL';
    private static final String NON_METHOD_B = '';

    /**
     * @description Create a summmary button
     *
     * @param campo1
     * @param campo2
     *
     * @see Schema
     *
     * @return
     */
    public Integer suma(final Integer campo1,final Integer campo2){

        List<Integer> listaString = new List<Integer>();
        for(Integer i=0; i<=563;i++){
            listaString.add(i);
            Account accountItem = [SELECT id FROM Account LIMIT 1];
        }

        String text ;
        Integer crmariable;
        return crmariable;



    }
    private void MostrarLog(List<Integer> listaString) {
            System.debug('Qp1 Lista de lases nievas llll con integracion existentes' + listaString);
        System.debug('Qp2 Lista de lases nievas llll con integracion existentes' + listaString);
           System.debug('Qp3 Lista de lases nievas llll con integracion existentes' + listaString);
    }


}